### Hospital Patient Flow & Care Analytics

You are a data analyst at a hospital. Management wants insights on:

- patient volume (daily/weekly)
- waiting times and length of stay
- readmissions
- department performance
- identifying risk/high-priority cases



Dataset 
A) Patient records (rows = patients)

Columns description:

- Age
- Department code (0=Emergency, 1=Outpatient, 2=Surgery, 3=Pediatrics)
- Severity score (1–5)
- Waiting time (minutes)
- Length of stay (hours)
- Readmitted within 30 days? (0=No, 1=Yes)
- Treatment cost 

### Hospital Patient Flow & Care Analytics

You are a data analyst at a hospital. Management wants insights on:

- patient volume (daily/weekly)
- waiting times and length of stay
- readmissions
- department performance
- identifying risk/high-priority cases



Dataset 
A) Patient records (rows = patients)

Columns description:

- Age
- Department code (0=Emergency, 1=Outpatient, 2=Surgery, 3=Pediatrics)
- Severity score (1–5)
- Waiting time (minutes)
- Length of stay (hours)
- Readmitted within 30 days? (0=No, 1=Yes)
- Treatment cost 

In [5]:
departments = np.array(["Emergency", "Outpatient", "Surgery", "Pediatrics"])

patients = np.array([
    [25, 0, 4, 60, 10, 0, 350],
    [60, 2, 5, 30, 48, 1, 4200],
    [40, 1, 2, 20,  2, 0, 150],
    [10, 3, 3, 15,  6, 0, 200],
    [72, 0, 5, 90, 24, 1, 1800],
    [33, 1, 1, 10,  1, 0, 80],
    [55, 2, 4, 45, 36, 0, 3500],
    [28, 0, 3, 50,  8, 0, 500],
    [65, 2, 5, 25, 72, 1, 9000],
    [18, 3, 2, 12,  3, 0, 120],
    [49, 1, 3, 35,  4, 0, 220],
    [80, 0, 4, 110, 30, 1, 2500],
])

days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])

daily_visits = np.array([
    [30, 50, 10, 20],
    [35, 55, 12, 18],
    [40, 60, 15, 22],
    [38, 58, 14, 25],
    [45, 65, 18, 30],
    [50, 40, 20, 15],
    [55, 35, 22, 10],
])

### Part 1 — Patient Summary KPIs

1. Total number of patients in the patients dataset.
2. Average age of patients.
3. Average waiting time (minutes).
4. Average length of stay (hours).
5. Total treatment cost for all patients.

### Part 2 — Weekly Flow (Daily visits table)

6. Total visits in the week (all departments combined).
7. Total visits per department for the week.
8. Which day had the highest total visits?
9. Which department had the highest visits on Saturday?

### Part 3 — Department Performance (Patients table)

10. Count how many patients are in each department (Emergency/Outpatient/Surgery/Pediatrics).
11. Compute average waiting time per department.
12. Compute average cost per department.
13. Which department has the highest average waiting time?

## Solutions

In [1]:
import numpy as np

departments = np.array(["Emergency", "Outpatient", "Surgery", "Pediatrics"])
patients = np.array([
    [25, 0, 4, 60, 10, 0, 350],
    [60, 2, 5, 30, 48, 1, 4200],
    [40, 1, 2, 20,  2, 0, 150],
    [10, 3, 3, 15,  6, 0, 200],
    [72, 0, 5, 90, 24, 1, 1800],
    [33, 1, 1, 10,  1, 0, 80],
    [55, 2, 4, 45, 36, 0, 3500],
    [28, 0, 3, 50,  8, 0, 500],
    [65, 2, 5, 25, 72, 1, 9000],
    [18, 3, 2, 12,  3, 0, 120],
    [49, 1, 3, 35,  4, 0, 220],
    [80, 0, 4, 110, 30, 1, 2500],
])
days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
daily_visits = np.array([
    [30, 50, 10, 20],
    [35, 55, 12, 18],
    [40, 60, 15, 22],
    [38, 58, 14, 25],
    [45, 65, 18, 30],
    [50, 40, 20, 15],
    [55, 35, 22, 10],
])

print("Patients:\n", patients)
print("Departments:\n", departments)
print("Days:\n", days)




# Part 1 — Patient Summary KPIs
print("\n=== Part 1: Patient Summary KPIs ===")
total_patients = patients.shape[0]
print(f"1. Total number of patients: {total_patients}")

avg_age = np.mean(patients[:, 0])
print(f"2. Average age: {avg_age:.2f}")

avg_waiting = np.mean(patients[:, 3])
print(f"3. Average waiting time (minutes): {avg_waiting:.2f}")

avg_los = np.mean(patients[:, 4])
print(f"4. Average length of stay (hours): {avg_los:.2f}")

total_cost = np.sum(patients[:, 6])
print(f"5. Total treatment cost: ${total_cost:,.2f}")

# Part 2 — Weekly Flow
print("\n=== Part 2: Weekly Flow (Daily visits table) ===")
total_visits_week = np.sum(daily_visits)
print(f"6. Total visits in the week: {total_visits_week}")

weekly_per_dept = np.sum(daily_visits, axis=0)
print("7. Total visits per department for the week:")
for dept, count in zip(departments, weekly_per_dept):
    print(f"   {dept}: {count}")

day_totals = np.sum(daily_visits, axis=1)
max_day_index = np.argmax(day_totals)
print(f"8. Day with highest total visits: {days[max_day_index]} ({day_totals[max_day_index]} visits)")

saturday_index = 5  # Sat is index 5
saturday_visits = daily_visits[saturday_index]
max_dept_sat = np.argmax(saturday_visits)
print(f"9. Department with highest visits on Saturday: {departments[max_dept_sat]} ({saturday_visits[max_dept_sat]} visits)")

# Part 3 — Department Performance
print("\n=== Part 3: Department Performance (Patients table) ===")
dept_codes = patients[:, 1].astype(int)
unique_depts, counts = np.unique(dept_codes, return_counts=True)
print("10. Number of patients per department:")
for code, count in zip(unique_depts, counts):
    print(f"    {departments[code]}: {count}")

# Compute average waiting time per department
avg_wait_per_dept = []
avg_cost_per_dept = []
for dept in range(4):
    mask = (dept_codes == dept)
    avg_wait = np.mean(patients[mask, 3])
    avg_cost = np.mean(patients[mask, 6])
    avg_wait_per_dept.append(avg_wait)
    avg_cost_per_dept.append(avg_cost)

print("11. Average waiting time per department (minutes):")
for dept, wait in zip(departments, avg_wait_per_dept):
    print(f"    {dept}: {wait:.2f}")

print("12. Average cost per department ($):")
for dept, cost in zip(departments, avg_cost_per_dept):
    print(f"    {dept}: ${cost:.2f}")

highest_wait_dept = np.argmax(avg_wait_per_dept)
print(f"13. Department with highest average waiting time: {departments[highest_wait_dept]} ({avg_wait_per_dept[highest_wait_dept]:.2f} minutes)")

Patients:
 [[  25    0    4   60   10    0  350]
 [  60    2    5   30   48    1 4200]
 [  40    1    2   20    2    0  150]
 [  10    3    3   15    6    0  200]
 [  72    0    5   90   24    1 1800]
 [  33    1    1   10    1    0   80]
 [  55    2    4   45   36    0 3500]
 [  28    0    3   50    8    0  500]
 [  65    2    5   25   72    1 9000]
 [  18    3    2   12    3    0  120]
 [  49    1    3   35    4    0  220]
 [  80    0    4  110   30    1 2500]]
Departments:
 ['Emergency' 'Outpatient' 'Surgery' 'Pediatrics']
Days:
 ['Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun']

=== Part 1: Patient Summary KPIs ===
1. Total number of patients: 12
2. Average age: 44.58
3. Average waiting time (minutes): 41.83
4. Average length of stay (hours): 20.33
5. Total treatment cost: $22,620.00

=== Part 2: Weekly Flow (Daily visits table) ===
6. Total visits in the week: 907
7. Total visits per department for the week:
   Emergency: 293
   Outpatient: 363
   Surgery: 111
   Pediatrics: 140
8. Day 